const expenses = [
    { id: "1", description: "Rent", amount: 1000 },
    { id: "2", description: "Groceries", amount: 150 },
    { id: "3", description: "Utilities", amount: 200 },
    { id: "4", description: "Transport", amount: 75 },
    { id: "5", description: "Internet", amount: 50 },
    { id: "6", description: "Gym Membership", amount: 40 },
    { id: "7", description: "Streaming Service", amount: 15 },
    { id: "8", description: "Dining Out", amount: 100 },
    { id: "9", description: "Entertainment", amount: 60 },
    { id: "10", description: "Insurance", amount: 120 },
    { id: "11", description: "Car Payment", amount: 300 },
    { id: "12", description: "Credit Card", amount: 200 },
    { id: "13", description: "Loan Payment", amount: 250 },
    { id: "14", description: "Pet Supplies", amount: 30 },
    { id: "15", description: "Medical Bills", amount: 100 },
    { id: "16", description: "Clothing", amount: 80 },
    { id: "17", description: "Savings", amount: 500 },
    { id: "18", description: "Gift", amount: 70 },
    { id: "19", description: "Travel", amount: 300 },
    { id: "20", description: "Office Supplies", amount: 25 },
    { id: "21", description: "Haircut", amount: 20 },
    { id: "22", description: "Subscription", amount: 10 },
    { id: "23", description: "Phone Bill", amount: 45 },
    { id: "24", description: "Gas", amount: 60 },
    { id: "25", description: "Household Items", amount: 35 },
    { id: "26", description: "Parking", amount: 15 },
    { id: "27", description: "Books", amount: 20 },
    { id: "28", description: "School Fees", amount: 400 },
    { id: "29", description: "Charity", amount: 50 },
    { id: "30", description: "Coffee", amount: 25 },
    { id: "31", description: "Snacks", amount: 10 },
    { id: "32", description: "Electronics", amount: 150 },
    { id: "33", description: "Furniture", amount: 200 },
    { id: "34", description: "Home Improvement", amount: 300 },
    { id: "35", description: "Tools", amount: 50 },
    { id: "36", description: "Workshop", amount: 100 },
    { id: "37", description: "Kids Activities", amount: 75 },
    { id: "38", description: "Fitness Equipment", amount: 150 },
    { id: "39", description: "Pet Care", amount: 60 },
    { id: "40", description: "Garden Supplies", amount: 30 },
    { id: "41", description: "Hobby", amount: 50 },
    { id: "42", description: "Laundry", amount: 15 },
    { id: "43", description: "Miscellaneous", amount: 20 },
    { id: "44", description: "Health Products", amount: 80 },
    { id: "45", description: "Beauty Products", amount: 40 },
    { id: "46", description: "Baby Products", amount: 100 },
    { id: "47", description: "Sports Equipment", amount: 120 },
    { id: "48", description: "Music", amount: 50 },
    { id: "49", description: "Art Supplies", amount: 30 },
    { id: "50", description: "Craft Supplies", amount: 25 },
  ];
  
  export default expenses;
  